### ISSUE TITLE
Dotfile concatenation

### ISSUE THREAD

**Issue by Lindenk** [FooSoft/homemaker#12]
So, after working on my own dotfile manager and realizing others existed, I found this homemaker which has most of the features I was working on. One big feature I would like to have though is dotfile concatenation as a way to resolve file conflicts. For instance, if I have the following .toml and two config files:

``` toml
[tasks.X]
    links = [
        ["X/.Xresources"]
    ]

[tasks.urxvt]
    links = [
        ["urxvt/.Xresources"]
    ]
```

`X/.Xresources`

```
Xcursor.theme: Adwaita
Xcursor.size:  16
```

`urxvt/.Xresources`

```
URxvt.perl-ext-common: default,clipboard

URxvt.depth: 32
URxvt.background: [75]#000000
URxvt*foreground: green
```

I would want them to be concatenated together and written to ~/.Xresources:

`.Xresources`

```
Xcursor.theme: Adwaita
Xcursor.size:  16

URxvt.perl-ext-common: default,clipboard

URxvt.depth: 32
URxvt.background: [75]#000000
URxvt*foreground: green
```

Of course, this might cause problems when updating configs because homemaker would need to run again to regenerate these files, so it might be better to use another name other than `links` for this specific feature for readability.
