### ISSUE TITLE
Add a links source directive to specify in which subfolder to search for files

### ISSUE THREAD

**Issue by ealprr** [FooSoft/homemaker#23]
With a dotfiles repository organize with folder (previous GNU stow user for example) like:
```
dotfiles
   |-git
      |-.gitconfig
   |-vim
      |-.vimrc
      |-.vim/
   |-bash
   | ...
```
A directive ``links-src`` or ``links-from`` would be very usefull. Instead of:

```toml
[tasks.vim]
    links = [
        [".vimrc", "vim/.vimrc"],
        [".vim", "vim/.vim"],
    ]
```
One could write:
```toml
[tasks.vim]
    links-src = "vim"
    links = [
        [".vimrc"],
        [".vim"],
    ]
```
