### ISSUE TITLE
Default source path search should fallback to filename without dot

### ISSUE THREAD

**Issue by ealprr** [FooSoft/homemaker#24]
```toml
[tasks.vim]
    links = [[".vimrc"]]
```

Would link vimrc file from the src folder (if no .vimrc exists).
