### ISSUE TITLE
Add dry-run option

### ISSUE THREAD

**Issue by travankor** [FooSoft/homemaker#26]
This option will print output of what the entered command will do but will not execute anything, printing any errors or conflicts. This would be especially useful for the `clobber` flag or generally testing a new configuration.

**Comment by FooSoft** [comment]
I've thought about this, but the problem is that half of homemaker, running commands, would not really work in a meaningful way with this option (especially when you consider dependencies and groups that run or don't run based on whether or not an application is installed).

**Comment by travankor** [comment]
Yeah, I wasn't sure if this was technically feasible at all. Just wondering though, do you test new bootstraps out inside chroots? That might be what I probably end up doing.

**Comment by FooSoft** [comment]
Honestly, I don't really have that great of a test plan. Between all my computers, I usually get enough "testing", but if I need to make sure that things work, I can just use a VM.

**Comment by therealklanni** [comment]
FYI, you can easily create a DIY dryrun option, like so:

```toml
[macros.install__dryrun]
prefix = ["echo", "sudo", "apt-get", "install"]

[macros.install]
prefix = ["sudo", "apt-get", "install"]
```

`homemaker -variant dryrun config.toml ~/dotfiles`
