### ISSUE TITLE
Conditional declarations?

### ISSUE THREAD

**Issue by imiric** [FooSoft/homemaker#4]
Hi!

First of all, thanks for your work on Homemaker. It's just what I was looking for to make my dotfiles a bit more manageable.

However, I was wondering what would be your suggestion for using Homemaker on multiple OSs regarding package names used in the installation commands?

For example, currently I'm working on Arch Linux at home, Ubuntu at work, and I'll be adding an OS X machine to the mix as well. Ideally, I'd want my dotfiles to be seamlessly managed on all three by the same tool.

For a few years now I've used [this Makefile](https://github.com/imiric/dotfiles/blob/master/Makefile#L14), and as you can see, it determines which OS it's running on to differentiate how packages are named and installed. I'm trying to move away from Make, for obvious reasons, but I'm not sure how to accomplish that using Homemaker.

I know I could create separate OS-specific tasks, but I want to avoid having to run something like `homemaker -task=vim-ubuntu conf src`, and would like for Homemaker to know what commands to run depending on the OS, so that, e.g. `homemaker -task=vim conf src` would work regardless of the OS I'm running.

Could something like this in the configuration file be supported?

``` toml
[macros.install%ubuntu]
  prefix = ["sudo", "apt-get", "install", "-y"]
[macros.install%arch]
  prefix = ["sudo", "pacman", "-S"]

[tasks.vim%ubuntu]
    cmds = [[
        "@install",
        "vim-nox"
    ]]
[tasks.vim%arch]
    cmds = [[
        "@install",
        "vim"
    ]]
```

In this case, key names with `%arch` or `%ubuntu` would be special directives for Homemaker, which would first identify the running OS, and then run commands, packages, or anything else conditionally as defined for that OS. Could these conditionals be somehow extended (e.g. the distro conditional could be one of many)? There's surely a better syntax than this, though.

What do you think? Is this something that Homemaker should/would support or is there a better (external?) solution I'm not seeing?

Thanks,

Ivan
